### ISSUE TITLE
Arabic Language is not getting translated , gives error saying "is not valid Latin-1"

### ISSUE THREAD

**Issue by kalpa8** [MicrosoftLearning/AI-102-AIEngineer#1]
# Module: AI-102-AIEngineer
#### Step: Use a Rest Interface - Step6

Description of issue:
Arabic Language is not getting translated , gives error as below: 

Error message:
"latin-1' codec can't encode characters in position 34-39: Body ('أهلاً،') is not valid Latin-1. Use body.encode('ut
f-8') if you want to send it encoded in UTF-8."

Repro steps:

1.Launch the Cognitive service
2. Call the Text Analytics language detection REST API 
3. Enter the Arabic text "أهلاً، كيف حالك"
4. Observe that above mentioned error is displayed.

**Comment by GraemeMalcolm** [comment]
So I've fixed this for the  **rest-client** apps (both C# and Python), and it seems to work by default for the Python **sdk-client** app. I'm having trouble with the C# version - even if I encode the input as an array of UTF-* bytes, it gets converted back to UTF-16 as soon as I assign it to a string. I'll keep researching...

**Comment by GraemeMalcolm** [comment]
I've reached out to the Text Analytics product team for help with this. Will update status when I have more info.

**Comment by GraemeMalcolm** [comment]
I added a note that non-Latin characters may not work in the Console app. Will continue to look for a resolution to the C# String encoding issue, but this will need to do for now.
