### ISSUE TITLE
pip install fails in module 11 (lab still works)

### ISSUE THREAD

**Issue by BerndtHamboeck** [MicrosoftLearning/AI-102-AIEngineer#101]
# Module: Module 11
#### Step: 3

Description of issue
pip install fails (latest bot framework might be the reason).

Repro steps:

pip install azure-ai-formrecognizer==3.0.0

result:

Installing collected packages: msrest, azure-ai-formrecognizer
  Attempting uninstall: msrest
    Found existing installation: msrest 0.6.10
    Uninstalling msrest-0.6.10:
      Successfully uninstalled msrest-0.6.10
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
botframework-connector 4.14.0 requires msrest==0.6.10, but you have msrest 0.6.21 which is incompatible.
botbuilder-schema 4.14.0 requires msrest==0.6.10, but you have msrest 0.6.21 which is incompatible.
Successfully installed azure-ai-formrecognizer-3.0.0 msrest-0.6.21       
PS C:\AI-102-AIEngineer-master\21-custom-form>

**Comment by GraemeMalcolm** [comment]
Version error/warning in pip install can generally be ignored, as long as ultimately the package installation succeeds. May be worth trying the latest v3.1.2 to see if that installs without the warning.

**Comment by drguthals** [comment]
@BerndtHamboeck - were you doing this on your own machine? 

On the Learn module sandbox it seems to be working no problem?

**Comment by GraemeMalcolm** [comment]
Closed as non-repro
