### ISSUE TITLE
Language service replacing Text Analytics resource

### ISSUE THREAD

**Issue by houbena** [MicrosoftLearning/AI-102-AIEngineer#106]
# Module: 6
#### Step: 2

Description of issue

Text Analytics is now part of the Language Service.
Please see screenshot
![image](https://user-images.githubusercontent.com/8375842/145052229-f5b3d726-e6f1-4823-ac6f-6f914ee3b522.png)

Step 2 should be updated with the navigation to the Language service.

**Comment by GraemeMalcolm** [comment]
We're working on a refresh to cover this (and LUIS and QnA Maker)

**Comment by GraemeMalcolm** [comment]
I've updated the lab to use the Language service (and Language Studio instead of the QnA Maker portal)

**Comment by ToshikazuOki** [comment]
"QnA Maker" remains at the beginning of Knowledge Base Training and Testing.

**Comment by GraemeMalcolm** [comment]
Thanks - fixed
