### ISSUE TITLE
Method TextInput_Prompt_Kz22lf_text() in Prompt for Text is not recognized

### ISSUE THREAD

**Issue by houbena** [MicrosoftLearning/AI-102-AIEngineer#107]
# Module: 7
#### Step: Add a button

Description of issue

Adding following code to the **Prompt for text** shows an error (please see screenshot below)

```
[Activity    
    Text = ${TextInput_Prompt_Kz22lf_text()}    
    SuggestedActions = Cancel
]
```
![Screenshot 2021-12-08 110346](https://user-images.githubusercontent.com/8375842/145189309-1f38ea9f-f26b-4bfb-a5a9-9ff5fc95abfb.png)

To fix it / work around it, I rolled back to the previous version of the code:

```
[Activity    
    Text = Enter your city.
    SuggestedActions = Cancel
]
```

**Comment by GraemeMalcolm** [comment]
Not sure what happened there - I reverted to the previous code
