### ISSUE TITLE
Missing comment in 20-OCR program.cs

### ISSUE THREAD

**Issue by houbena** [MicrosoftLearning/AI-102-AIEngineer#108]
# Module: 11
#### Step: 03

Description of issue
I received the feedback from a non-developer attendee that he didn't know were to put the code starting with 
```
// Use Read API to read text in image
```

Adding that comment to the provided app (like for previous instructions) could makes it easier to go through this task.

**Comment by GraemeMalcolm** [comment]
The instructiion is "find the GetTextRead function, and under the existing code that prints a message to the console, add the following code" - a student who meets the prerequisites for this developer-targeted course should be able to follow this.
