### ISSUE TITLE
"Deploy and Test the Bot" section gives error in Lab 13

### ISSUE THREAD

**Issue by kalpa8** [MicrosoftLearning/AI-102-AIEngineer#11]
# Module: Create a Bot with the Bot Framework SDK
#### Step: 1

Description of issue
Error "Zip deployment failed" is displayed as given below while deploying the bot
**Error Details:**
Deployment endpoint responded with status code 202
Configuring default logging for the app, if not already enabled
Zip deployment failed. {'id': '3e726d92f6034fe5b253866adb6c1dda', 'status': 3, 'status_text': '', 'author_email': 'N/A', 'author': 
'N/A', 'deployer': 'Push-Deployer', 'message': 'Created via a push deployment', 'progress': '', 'received_time': '2021-01-28T18:44:22.5607085Z', 'start_time': '2021-01-28T18:44:23.7717434Z', 'end_time': '2021-01-28T18:47:33.6878712Z', 'last_success_end_time': None, 'complete': True, 'active': False, 'is_temp': False, 'is_readonly': True, 'url': 'https://newwebappks.scm.azurewebsites.net/api/deployments/latest', 'log_url': 'https://newwebappks.scm.azurewebsites.net/api/deployments/latest/log', 'site_name': 'newwebappks'}. Please run the command az webapp log deployment show -n newwebappks -g tear-down

Repro steps:

1. Create a bot
2. Package the code files to .zip
3. Deploy the Bot using below command
 "az webapp deployment source config-zip --resource-group "YOUR_RESOURCE_GROUP" --name "YOUR_WEB_APP_NAME" --src "TimeBot.zip"

**Comment by GraemeMalcolm** [comment]
Resolved - need to zip files using Windows UI
