### ISSUE TITLE
Enable custom question answering in speech lab needs update

### ISSUE THREAD

**Issue by Theelepel** [MicrosoftLearning/AI-102-AIEngineer#115]
#### Step: 00

Description of issue
![image](https://user-images.githubusercontent.com/28536066/148368009-9747a6e1-a15d-4e19-8a42-4361e53a9acc.png)

New step needs to be added here. During -Create a question answering project- it will bring you to the portal to create an additional resource

**Comment by madiepev** [comment]
@Theelepel under Create a Language resource, step 3, you are asked to enable custom question answering. Could it be you skipped this and that's why you are prompted later?
