### ISSUE TITLE
Speech to Text translation from "en" to "hi" does not display correctly in Lab8

### ISSUE THREAD

**Issue by kalpa8** [MicrosoftLearning/AI-102-AIEngineer#12]
# Module: speech-translation
#### Step: 2

Description of issue
On translating English audio to Hindi , the hindi text is not displayed correctly

Repro steps:

1.Use speech to text service
2.Select "hi" language 
3.Speak using microphone
4. Observe that Hindi language text is not displayed correctly.

**Comment by GraemeMalcolm** [comment]
Added note to that effect
