### ISSUE TITLE
Module 7 requires Cognitive Search

### ISSUE THREAD

**Issue by AndrewConniff** [MicrosoftLearning/AI-102-AIEngineer#122]
# Module: 07
#### Step: 03

Description of issue
Azure requires Cognitive search on this step - it takes a few minutes to create one but the instructions do not mention it - the lab is able to finish but text needs to be updated
Repro steps:

1.
1.
1.

**Comment by GraemeMalcolm** [comment]
The instructions tell you to select Custom Question Answering, which then adds settings for Azure Search to the wizard  (see step 3 in the "Create a Language resource" procedure.

Aren't you seeing those options?

**Comment by GraemeMalcolm** [comment]
Closing as non-repro
