### ISSUE TITLE
Broken link in lab 21 21-form-recognizer.md

### ISSUE THREAD

**Issue by rockberts** [MicrosoftLearning/AI-102-AIEngineer#124]
# Module:  Module 11 - Reading Text in Images and Documents
#### Step: After the step number three, the paragraph says "To train with labels, you will need to [create the labeled files](https://docs.microsoft.com/azure/cognitive-services/form-recognizer/quickstarts/label-tool?tabs=v2-0)." 

Description of issue

This links doesn't work

Repro steps:

1. Go to the task - step click in the link "create labeled files"
1.
1.

**Comment by madiepev** [comment]
Thanks for the feedback. The link should work now!
