### ISSUE TITLE
Module 2 Lab 2 Task 3 Step 6 It always detect English but no clues on what went wrong.

### ISSUE THREAD

**Issue by donaldcng** [MicrosoftLearning/AI-102-AIEngineer#129]
# Module: 02
#### Step: 06

Description of issue: Always show the language as "English" but no errors. Is there any logs or insights to understand what was the problem? 
![2022-03-29 08_57_58-AsPowerBar](https://user-images.githubusercontent.com/100983678/160511700-0d032e56-db32-43ea-92f4-4f2c99054f56.png)

**Comment by ivorb** [comment]
Hi @donaldcng, it does appear it's not doing the right thing! Usually, the default is English if there is an error, so I'd recommend checking the connection/service you set up. If you use the `rest-test.cmd` that was explained earlier in this lab and change the input to "Hola" or "Bonjour", that output does give a bit more information. I was able to set up a connection and test in that way, and verified the correct results were returned.
