### ISSUE TITLE
White oval circle appears on clicking the data points in the confusion matrix

### ISSUE THREAD

**Issue by kalpa8** [MicrosoftLearning/AI-102-AIEngineer#13]
# Module: Create a Language Understanding App
#### Step: 5

Description of issue
On clicking the different data points in the confusion matrix several times we observe that an white oval circle appears which overlaps on the data points

Repro steps:

1.Create a Language Understanding app
2.Add Intents, Entities and train the app
3.Perform Batch testing and click on the "see results"
4. In the confusion matrix that appears , click on the different data points
Observe that after some time the oval circle appears , which overlaps on the data points.

**Comment by GraemeMalcolm** [comment]
Added a note explaining this issue
