### ISSUE TITLE
Lab 23: Cannot deploy function app with Runtime .Net Core3.1

### ISSUE THREAD

**Issue by donaldcng** [MicrosoftLearning/AI-102-AIEngineer#130]
# Module: 12
#### Step: 02

Description of issue
During the steps of "Create an Azure Function for a custom skill", there is no options to deploy the Function app with RUntime .Net Core3.1. only .Net 6 available.
![2022-03-31 21_16_05-AsPowerBar](https://user-images.githubusercontent.com/100983678/161065578-cd48eeab-dcff-4c93-a9d3-d81127d29639.png)

**Comment by GraemeMalcolm** [comment]
Yup - looks like Functions were updated to require .NET 6. Lab is broken until we create a fix...

**Comment by GraemeMalcolm** [comment]
OK, as a temporary workaround, I updated the lab to create a Node.JS function in the portal. When we next do a major refresh that involves updating the VM< we'll ensure that the required .NET components are installed so we can revert to using C# or Python as preferred.

Thanks @donaldcng  for calling this one out!
