### ISSUE TITLE
Lab:24 Setup script is not stable, normally cannot complete as whole

### ISSUE THREAD

**Issue by donaldcng** [MicrosoftLearning/AI-102-AIEngineer#131]
# Module: 12
#### Step: 12

Description of issue: Setup script is not stable, normally cannot complete as whole. Tried few time and cannot complete.
And also suggest to guide learner to delete all resources under resources group to re-run.

![vlcsnap-2022-03-31-21h46m26s399](https://user-images.githubusercontent.com/100983678/161071005-418d052f-86f9-464c-87b0-8034249aadf8.png)

**Comment by GraemeMalcolm** [comment]
I can't repro the error you're seeing - the script runs consistently in testing.
The instructions already include a note to check variables and try again - deleting any orphaned resources makes no difference (next time it will generate a different unique suffix)
