### ISSUE TITLE
ocr instructions mention only English for read API

### ISSUE THREAD

**Issue by douwevandenberg** [MicrosoftLearning/AI-102-AIEngineer#134]
# Module: 11
#### Step: 1

Description of issue
In 20-ocr the description of the Read API needs an update. It mentions the following:

"The Read API uses a newer text recognition model than the OCR API, and performs better for larger images that contain a lot of text. It also supports text extraction from .pdf files, and can recognize both printed text (in multiple languages) and handwritten text (in English)."

If you check https://docs.microsoft.com/en-us/azure/cognitive-services/computer-vision/language-support and other pages in the docs, you will find that read should now support all 9 handwritten languages also supported by ocr. 

Repro steps:

1. Irrelevant

**Comment by ivorb** [comment]
Thanks for reporting the issue! I'll get this taken care of

**Comment by ivorb** [comment]
Fixed
