### ISSUE TITLE
Bot Framework Emulator Update Download does not complete

### ISSUE THREAD

**Issue by Yorik1971** [MicrosoftLearning/AI-102-AIEngineer#138]
# Module: 00
#### Step: 1

Description of issue
The updating of the Bot Framework Emulator application does not show any download progress indicator and never actually completes the download process.  No logs or error messages could be found to help troubleshoot the issue.

Repro steps:

1. Start the **Bot Framework Emulator**
2. If prompted to install an update do so for the currently logged in user
3. If not prompted to install an update select the **Check for update** option on the **Help** menu

NOTE: The download appears to never actually initiate as network bandwidth is not affected and no temporary download file is created

![image](https://user-images.githubusercontent.com/107193818/176190307-e2da4b5e-b4a8-4dda-b0f4-69806d9db9dc.png)
![image](https://user-images.githubusercontent.com/107193818/176190641-9c5e7466-ca50-451b-ad64-b86828eab244.png)

**Comment by GraemeMalcolm** [comment]
Does the rest of the lab work successfully with the currently installed version?

**Comment by Yorik1971** [comment]
yes, the lab can be successfully completed without updating the version of the Bot Framework Emulator.

**Comment by GraemeMalcolm** [comment]
OK, thanks - we'll investigate what's going on with the update process, but at least it's not a complete blocker.

**Comment by ivorb** [comment]
This appears to be an issue outside of these labs, and is known to the product team. I've asked for an update on the issue in their repo, but it will need to be fixed on their end. Since the lab works fine with the current version, closing this issue

Can follow their issue here: https://github.com/microsoft/BotFramework-Emulator/issues/2347

**Comment by ivorb** [comment]
To make this clearer to future learners, I included a note to continue with the current version if download of the update fails
