### ISSUE TITLE
Lab 14. Endpoint Errors with Luis

### ISSUE THREAD

**Issue by janeroughan** [MicrosoftLearning/AI-102-AIEngineer#14]
# Module: 00
#### Step: 04

Description of issue
Created LUIS in Portal in Australia, I get an error when restarting the bot. Screen shot

![image](https://user-images.githubusercontent.com/24537110/106279103-04c89900-6290-11eb-901a-472bc4535772.png)

Then use LUIS in westus, I get an error later after running in the emulator. 2 Screen shots: 1 is settings and 2 is error:
![image](https://user-images.githubusercontent.com/24537110/106279187-26c21b80-6290-11eb-9fd5-772125cd345c.png)

![image](https://user-images.githubusercontent.com/24537110/106279217-2e81c000-6290-11eb-86b4-32c10cc9c7db.png)

Note the difference in the end pointname.

Repro steps:

1.
1.
1.

**Comment by GraemeMalcolm** [comment]
It's because you've added a LUIS _endpoint_ key rather than just a LUIS _Authoring_ key. I've clarified this in the instructions
