### ISSUE TITLE
Mod 10 - Lab 19 - Python code error: (InvalidRequest)

### ISSUE THREAD

**Issue by mpaione** [MicrosoftLearning/AI-102-AIEngineer#141]
# Module: 10
#### Step: 00

Description of issue
Added Python code to Get Faces
Execution of  python analyze-faces.py
Menu option shown:
1: Detect faces
2: Compare faces
3: Train a facial recognition model
4: Recognize faces
5: Verify a face
Any other key to quit

Option1: Detect faces selected, then showing Detecting faces in images\people.jpg next error message:
(InvalidRequest) Invalid request has been sent.

**Comment by ivorb** [comment]
Hi @mpaione, unfortunately that vague of an error could be a lot of things, and without the code you're using it's hard to diagnose. Within the lab environment I was able to complete this lab as expected, with no errors. Happy to take a look at your code if you put it in a fork, but as it stands this lab doesn't appear to have issues

**Comment by mpaione** [comment]
Hello @ivorb I'm using - and students at the course as well- the code provided here. I'm sending Python code use during current AI102 I'm teaching. From a population of 10 students , half of them used Python version and all failed at same point. C# version is working without problems.
We think it's a path related situation due to seem that the image file is not able to get it.
Adding face-api folder to allow you to check and test.

Let me know, students are waiting for an answer.

Best regards,

[face-api.zip](https://github.com/MicrosoftLearning/AI-102-AIEngineer/files/9071527/face-api.zip)

**Comment by ivorb** [comment]
@mpaione As Graeme mentioned in the other issue, there is a change for Face API that requires requesting access to use, aligning with new Responsible AI guidelines (what I had seen when testing yesterday was due to existing instances being depreciated but still working). That is not realistic for a classroom setting, we realize, and are working to figure out a better solution.

**Comment by mpaione** [comment]
Thanks Ivor.


Marcos Paione
***@***.******@***.***>
