### ISSUE TITLE
Module 07, unable to run the cookiecutter

### ISSUE THREAD

**Issue by Reddy0980** [MicrosoftLearning/AI-102-AIEngineer#142]
# Module: 07
#### Step: 01

Description of issue
when we running the code in Python we are getting the following error, we are using the python version 3.9.7
![image](https://user-images.githubusercontent.com/95687117/177819085-b5d1cf56-1acc-4564-bda0-47c0d34c58d5.png)

Repro steps:

1.
1.
1.

**Comment by GraemeMalcolm** [comment]
Are you using your own PC or the provided hosted VM?

**Comment by GraemeMalcolm** [comment]
It looks like you're using a PowerShell console -  the lab environment uses a Bash shell.

**Comment by ivorb** [comment]
@Reddy0980, on the hosted lab environment this works in PowerShell, bash, and cmd, however Graeme is correct - we can't provide support for your own environment. If I had to guess, the pip install from the step prior didn't complete, and `cookiecutter` wasn't installed for you, thus the error you see. Try verifying that completed successfully, or please use the hosted VM provided.
