### ISSUE TITLE
Mod 10 - Python - Prepare to use the Face SDK - fail

### ISSUE THREAD

**Issue by mpaione** [MicrosoftLearning/AI-102-AIEngineer#143]
Hello @ivorb I'm using - and students at the course as well- the code provided here. I'm sending Python code use during current AI102 I'm teaching. From a population of 10 students , half of them used Python version and all failed at same point. C# version is working without problems.
We think it's a path related situation due to seem that the image file is not able to get it.
Adding face-api folder to allow you to check and test.

Let me know, students are waiting for an answer.

Best regards,

[face-api.zip](https://github.com/MicrosoftLearning/AI-102-AIEngineer/files/9071527/face-api.zip)

_Originally posted by @mpaione in https://github.com/MicrosoftLearning/AI-102-AIEngineer/issues/141#issuecomment-1178863457_

**Comment by GraemeMalcolm** [comment]
So, from June 11th, the Face service (and Video Indexer) are restricted to organizations who have explicitly requested access. See https://docs.microsoft.com/en-us/azure/cognitive-services/computer-vision/overview-identity
This is likely the cause of the issue. Nothing we can do I'm afraid.

**Comment by mpaione** [comment]
Thanks for the reply, if that the situation the lab will fail in C# as well and it’s not the situation, lab fail on Python code only, C# works fine.


Marcos Paione
***@***.******@***.***>

**Comment by GraemeMalcolm** [comment]
Yes. Thank you.
We're working on that.
