### ISSUE TITLE
Module 7 : Create a Bot with the Bot Framework SDK

### ISSUE THREAD

**Issue by manishrps** [MicrosoftLearning/AI-102-AIEngineer#147]
# Module: 07
#### Step: 01/Python command
When I was running the python command "python app.py", getting an error, saying " File "C:\Python39\lib\site-packages\botbuilder\core\integration\aiohttp_channel_service_exception_middleware.py", line 20, in aiohttp_error_middleware
    response = await handler(request)
  File "C:\Python39\lib\site-packages\aiohttp\web_urldispatcher.py", line 931, in _handle
    raise self._http_exception
aiohttp.web_exceptions.HTTPNotFound: Not Found"

![image](https://user-images.githubusercontent.com/55728764/179494537-919d53b8-3a57-499c-93f3-e073aa81d4c8.png)
Could you please help!

Thank you!

@sharechiwai @otaiga @drguthals @cavefish @mdragt

**Comment by ivorb** [comment]
@manishrps is this on the hosted environment, or your machine?

The error looks to be an integration between `aiohttp` and `botbuilder-core`, can you verify that both of those are installed correctly in the previous `pip install` step? The app runs as expected in the hosted lab environment, so I'm suspecting it's an issue with the installation of the packages, or an inability to connect to the correct URL (internet connectivity issues?)

![image](https://user-images.githubusercontent.com/11559977/179845890-cf25dda7-a56f-42b2-b2ce-b11f348542cc.png)

**Comment by manishrps** [comment]
@ivorb I have followed all the steps as mentioned in the lab guide and installed the required packages successfully, but still, I'm facing an issue at this step. could you please help me with the packages which I have missed or any other workaround?

Thank you!

**Comment by ivorb** [comment]
@manishrps can you please verify what environment you're working in? Hosted lab, or personal machine?

Please also upload your code to a fork so I can see what you have and try to replicate the problem
