### ISSUE TITLE
"ImageFileCreateBatch object is not iterable" error while using training api to upload images

### ISSUE THREAD

**Issue by kalpa8** [MicrosoftLearning/AI-102-AIEngineer#15]
# Module: AI 102- lab18
#### Step: 9

Description of issue
"ImageFileCreateBatch object is not iterable" error while using training api to upload images

Repro steps:
1.Create a Custom Vision Project
2.Use the CustomVisionTrainingClient api to upload images 
Observe that the error "ImageFileCreateBatch object is not iterable"  is displayed

**Comment by GraemeMalcolm** [comment]
Fixed by updating package version to 3.1.0
