### ISSUE TITLE
Mod 07 Bot .NET error (missing framework)

### ISSUE THREAD

**Issue by sanpietro** [MicrosoftLearning/AI-102-AIEngineer#152]
# Module: 07
### Task: Test the bot in the Bot Framework Emulator: https://github.com/MicrosoftLearning/AI-102-AIEngineer/blob/master/Instructions/13-bot-framework.md#test-the-bot-in-the-bot-framework-emulator

Description of issue

C#: when we dotnet run, we get an error that we need to download the .NET framework and provides a link to do so. 

.

**Comment by GraemeMalcolm** [comment]
Are you running the lab in the provided hosted environment?

**Comment by sanpietro** [comment]
Hey Graeme!

I apologize, I was logged in with my personal email. It's Joe San Pietro.
I'm delivering AI-102 this week...and, yes, it is the Cloudslice for Lab 13.

Feel free to ping me on Teams or wherever is easiest for you.

Thanks!
Joe

**Comment by GraemeMalcolm** [comment]
@ivorb, can you investigate?

**Comment by ivorb** [comment]
This update should enable learners to continue with the lab as written - confirmed it works on Learn labs today. Thanks for reporting @sanpietro!
