### ISSUE TITLE
Lab 9b - Language Understanding (Preview)

### ISSUE THREAD

**Issue by annav88** [MicrosoftLearning/AI-102-AIEngineer#157]
# Module: 03
#### Step: 04

Description of issue

In the instruction the POST request in the instruction does not correspond to what we have in the Language portal, there is an extra PARTICIPANTID property. Could you please update the instruction with what has to be insterted for a sample PARTICIPANTID value

Repro steps:

See the screenshot

Thank you,
Anna

**Comment by annav88** [comment]
![error002](https://user-images.githubusercontent.com/83666021/192503464-f74f129a-0c3f-43c9-849c-493ebdd1cc62.png)

**Comment by ivorb** [comment]
I've got the update for the participant ID, but by just giving it "1" I was able to query my deployment. Could you try "1" as the participant ID, and tell me what error is returned for you?
