### ISSUE TITLE
Lab 13 initial code set up does not work

### ISSUE THREAD

**Issue by CalebWelch** [MicrosoftLearning/AI-102-AIEngineer#159]
### Task: Test the bot in the Bot Framework Emulator

Description of issue
Starter template code does not work.
Repro steps:
1. Clone repo
2. follow the instructions given in the lab (cookiecutter https://github.com/microsoft/botbuilder-python/releases/download/Templates/echo.zip)
3.Start app
4. go to the localhost and port defined and go to api/messages (localhost:3978/api/messages)
5. No chat pane pops up like the lab mentions, cannot send messages to the bot with requests using something like postman  either

 ![image](https://user-images.githubusercontent.com/14021660/194365772-d6134c61-f35e-4e62-b754-0edc8c8ccd19.png)
```$ python app.py 
======== Running on http://localhost:3978 ========
(Press CTRL+C to quit)
Traceback (most recent call last):
  File "F:\anaconda2\envs\tf_gpu_env\lib\site-packages\botbuilder\core\integration\aiohttp_channel_service_exception_middleware.py", line 20, in aiohttp_error_middleware
    response = await handler(request)
  File "F:\anaconda2\envs\tf_gpu_env\lib\site-packages\aiohttp\web_urldispatcher.py", line 931, in _handle
    raise self._http_exception
aiohttp.web_exceptions.HTTPMethodNotAllowed: Method Not Allowed
Traceback (most recent call last):
  File "F:\anaconda2\envs\tf_gpu_env\lib\site-packages\botbuilder\core\integration\aiohttp_channel_service_exception_middleware.py", line 20, in aiohttp_error_middleware
    response = await handler(request)
  File "F:\anaconda2\envs\tf_gpu_env\lib\site-packages\aiohttp\web_urldispatcher.py", line 931, in _handle
    raise self._http_exception
aiohttp.web_exceptions.HTTPNotFound: Not Found


botbuilder-core                 4.14.2
botbuilder-schema               4.14.2
botframework-connector          4.14.2
botframework-streaming          4.14.2
aiohttp                         3.8.3
asyncio                         3.4.3
cookiecutter                    1.7.0

**Comment by GraemeMalcolm** [comment]
@CalebWelch , are you using the hosted VM on Microsoft Learn or the lab profile provided in an instructor-led course?

**Comment by CalebWelch** [comment]
@GraemeMalcolm 
I tried both locally and the VM provided via the course https://learn.microsoft.com/en-us/training/modules/design-bot-conversation-flow/6-exercise-create-a-bot and got the same issue on both

**Comment by GraemeMalcolm** [comment]
OK, thanks - we'll investigate and report back...

**Comment by GraemeMalcolm** [comment]
Hmm - non-repro for me. Are you sure when you open the bot in the emulator you're specifying the URL where your bot is running (in my case it's `http://localhost:3978/api/messages`, but the port number might vary - it's displayed when you run the `python app.py` command.

**Comment by CalebWelch** [comment]
![Code_MjVEPBPZSv](https://user-images.githubusercontent.com/14021660/194375380-df35ac60-0176-48db-a374-fcbb94485787.gif)
Yes, I made sure its the correct address and port

**Comment by GraemeMalcolm** [comment]
The file paths in your screenshot don't match the hosted VM. Can you record what happens when you use the hosted VM environment?

**Comment by CalebWelch** [comment]
![image](https://user-images.githubusercontent.com/14021660/194381323-c8388830-fb57-4520-9711-58a56f292924.png)
Same issue in the VM

**Comment by GraemeMalcolm** [comment]
So, here's what I get in the hosted VM from Learn.
I have no idea why you're getting a different result.
![image](https://user-images.githubusercontent.com/11771134/194383625-c1cbda36-62a1-43ed-a11f-b12555565bad.png)

**Comment by GraemeMalcolm** [comment]
Ah - yes I do. It looks like you're trying to test the bot using a web browser instead of Bot Framework Emulator.

**Comment by CalebWelch** [comment]
Ah I see I missed a step, although I'm still having an issue. there's no start up message, and the message fails to send. No errors are popping up in the console either 
![image](https://user-images.githubusercontent.com/14021660/194391571-d44be8e0-0985-46d3-9828-ba53c4b85092.png)

**Comment by GraemeMalcolm** [comment]
In Bot Framework Emulator, you've connected to http://localhost:3980/api/messages, but your bot is running on http://localhost:3978/api/messages.
