### ISSUE TITLE
Error! Missing "/" in the url for translate text. Causes error for attendees

### ISSUE THREAD

**Issue by dtarek1** [MicrosoftLearning/AI-102-AIEngineer#162]
# Module: 04
#### Step: 02
Description of issue

TThe code is missing a "/" in the url for the Detect language and Translate text APIs. Please either add it to the instructions code or to the github code after the endpoint
. This caused error when the  code runs

// Use the Translator detect function
object[] body = new object[] { new { Text = text } };
var requestBody = JsonConvert.SerializeObject(body);
using (var client = new HttpClient())
{
    using (var request = new HttpRequestMessage())
    {
        // Build the request
        string path = "detect?api-version=3.0"; **### ----- this should be "/detect?api-version=3.0";** 
        request.Method = HttpMethod.Post;
        request.RequestUri = new Uri(translatorEndpoint + path);
        request.Content = new StringContent(requestBody, Encoding.UTF8, "application/json");
        request.Headers.Add("Ocp-Apim-Subscription-Key", cogSvcKey);
        request.Headers.Add("Ocp-Apim-Subscription-Region", cogSvcRegion);

        // Send the request and get response
        HttpResponseMessage response = await client.SendAsync(request).ConfigureAwait(false);
        // Read response as a string
        string responseContent = await response.Content.ReadAsStringAsync();

        // Parse JSON array and get language
        JArray jsonResponse = JArray.Parse(responseContent);
        language = (string)jsonResponse[0]["language"]; 
    }
}

**Comment by dtarek1** [comment]
Or it should be added here in the github code:

private static string translatorEndpoint = "https://api.cognitive.microsofttranslator.com";  **### ----> should be "https://api.cognitive.microsofttranslator.com/";**

**Comment by ivorb** [comment]
Fixed with above commit, thanks for pointing out.
