### ISSUE TITLE
Issue: Not able to create container instance for Azure Congnative Service for Language

### ISSUE THREAD

**Issue by bhadreshpsavani** [MicrosoftLearning/AI-102-AIEngineer#168]
# Module: AI-102-AIEngineer/Instructions/
#### Step: 01

the container instance
`mcr.microsoft.com/azure-cognitive-services/textanalytics/language:1.1.013570001-amd64` is not getting found while creating the container instance.

I also checked but the above URL is not available in the https://mcr.microsoft.com/en-us/product/azure-cognitive-services/textanalytics/language/tags. Its not available there

**Comment by ivorb** [comment]
Can you post your error here? I was able to create a container instance with the image in the instructions - although that image is old and no longer listed there. Is it the create step of the instance that fails?

That said, nothing stopping us from using the latest image for this lab for just language detection. I'll update the lab accordingly

**Comment by bhadreshpsavani** [comment]
Hi @ivorb,
I am getting below error,
![image](https://user-images.githubusercontent.com/26653468/207411421-c1351261-c1f8-4889-93c4-2cdf6a4d8f53.png)

I also tried creating Container instance with `docker pull mcr.microsoft.com/azure-cognitive-services/textanalytics/language:3.0.58166773-onprem-amd64`, I was able to create the instance but when i trigger rest api call it was giving time out thing,

Even i checked it for its swagger url like this `http://<your_ACI_IP_address_or_FQDN>:5000/swagger/index.html` i was able to access the swagger page but there also it was giving timeout error.
