### ISSUE TITLE
[Probable Issue] Need to pass `audio_config` explicitly in the lab `08-translate-speech` lab

### ISSUE THREAD

**Issue by bhadreshpsavani** [MicrosoftLearning/AI-102-AIEngineer#172]
# Module: 08-translate-speech
#### Step: python code

Description of issue:
if we pass it like this,
```python
translator = speech_sdk.translation.TranslationRecognizer(translation_config, audio_config)
```
it gives exception `5` and program executions
```output
Ready to translate from en-US

Enter a target language
 fr = French
 es = Spanish
 hi = Hindi
 Enter anything else to stop
hi
works
5
```
when i checked the official docunmentation for [TranslationRecognizer](https://learn.microsoft.com/en-us/python/api/azure-cognitiveservices-speech/azure.cognitiveservices.speech.translation.translationrecognizer?view=azure-python) it says,
```python
TranslationRecognizer(translation_config: azure.cognitiveservices.speech.translation.SpeechTranslationConfig, \
auto_detect_source_language_config: Optional[azure.cognitiveservices.speech.languageconfig.AutoDetectSourceLanguageConfig] = None, audio_config: Optional[azure.cognitiveservices.speech.audio.AudioConfig] = None)
```
so `audio_config` is third optional argument,
below code works fine
```python
translator = speech_sdk.translation.TranslationRecognizer(translation_config, audio_config = audio_config)
```
Note: i am using `azure-cognitiveservices-speech 1.24.2` since the version mentioned in the tutorial was not compatible with `python 3.11` may be in the tutorial we can specify which python version was used for creating the tutorial so that the pip dependecy works fine

**Comment by ivorb** [comment]
Just fixed via commit
