### ISSUE TITLE
Lab Instruction should tell to hit 'enter' button to add Utterance in Language Studio

### ISSUE THREAD

**Issue by msftnutta** [MicrosoftLearning/AI-102-AIEngineer#179]
# Module: 9b
#### Step: 2

Description of issue

Without a 'Add' button, adding utterances could be confusing.

In order to create records for utterances, need to be clearer on how to add each record by hitting enter button to add.

**Comment by GraemeMalcolm** [comment]
Too explicit - we want them to think about what they're doing.
