### ISSUE TITLE
no results for 'quiet hotel in New York'

### ISSUE THREAD

**Issue by true-while** [MicrosoftLearning/AI-102-AIEngineer#18]
#### Step: 8

Description of issue

_In the Search box, enter a new search for **quiet hotel in New York** and review the results._

Repro steps:

in search from the web site does not return any results for request "quiet hotel in New York", but return for "quiet hotel" only 1 hotel in London

**Comment by GraemeMalcolm** [comment]
Not repor - I'm guessing you missed setting a field to Searchable earlier in the exercise
