### ISSUE TITLE
Lab 10b, the prediction url given from the studio itself isn't working.

### ISSUE THREAD

**Issue by msftnutta** [MicrosoftLearning/AI-102-AIEngineer#181]
#### Step: 3

Description of issue

Repro steps:

1. Retrieve the Prediction URL directly from language studio, and its URL ending with ...preview
2. paste in .env file
3. run the program, and see error 404

the instruction should inform to use the Endpoint retrieved from Azure Portal - Language Service - Keys and Endpoints

**Comment by GraemeMalcolm** [comment]
Looks like there's a new version of the SDK - the old preview one may now be broken.
We should update the instructions and code so it works (obviously!) and also remove "(preview)" from the folder name as this is now the "current" language model service.

**Comment by ivorb** [comment]
addressed with PR #185
