### ISSUE TITLE
Lab 12 - Steps are ordered incorrectly.

### ISSUE THREAD

**Issue by msftnutta** [MicrosoftLearning/AI-102-AIEngineer#182]
#### Step: 4

Description of issue

The question and answer must be saved first, before **＋ Add alternative phrase**  menu an be seen

Repro steps:

![image](https://user-images.githubusercontent.com/98095529/228171752-789b3511-43ed-4429-8f10-93fb4a85aa38.png)

see the screen shot below, there is no option to add an alternative pharse.

![image](https://user-images.githubusercontent.com/98095529/228172123-693dddbf-9109-4d40-9c7d-70fa7d5ed07c.png)

**Comment by GraemeMalcolm** [comment]
Fixed
