### ISSUE TITLE
Receive an error when running sdk-client.py

### ISSUE THREAD

**Issue by lneukirchner** [MicrosoftLearning/AI-102-AIEngineer#186]
# Module: 01
#### Step: 05

Description of issue

I get an error when I attempt to run the sdk-client.py script it gives me an error stating: 

>ModuleNotFoundError: No module named 'azure'

I believe this is because the script hasn't been updated to reflect the deprecation of a single azure meta-module.

Repro steps:

1. Inside of the sdk-client folder inside of the Python folder for Module 01, Run >python sdk-client.py

**Comment by Mihai-Ac** [comment]
Hello  @lneukirchner 
Can you please confirm you ran the  pip install azure-ai-textanalytics==5.1.0 command from Step 2? This error pops up if that component is not installed.

If you are still getting an error after installing the package, please take a screenshot and send it to us.

Best regards,
Mihai
