### ISSUE TITLE
AI-102-04 curl empty server response

### ISSUE THREAD

**Issue by MrRobboWilliamson** [MicrosoftLearning/AI-102-AIEngineer#187]
# Module: 05
#### Step: 03

Description of issue
Hi - I followed the lab instructions carefully and have a running container instance, but when executing the rest-test.cmd file with the container id I get a curl error: "response is empty".

Do I need to be logged into azure cli on the client side?

Repro steps:
1. follow lab steps

**Comment by ivorb** [comment]
still investigating a workaround to enable this scenario to avoid this issue. Will update asap

**Comment by prabhjotsinghbakshi** [comment]
the lab worked for me with this image link -
mcr.microsoft.com/azure-cognitive-services/textanalytics/language:1.1.013570001-amd64

**Comment by mkems** [comment]
Issue still exists with the latest version - please update the instructions.

**Comment by ivorb** [comment]
This should be fixed as of today.

**Comment by prabhjotsinghbakshi** [comment]
@ivorb It is Not Fixed in LOD ( but yes it works fine in Pay as you go account with 12 GB ram for container)
