### ISSUE TITLE
Python Speech SDK version error

### ISSUE THREAD

**Issue by 1amitn** [MicrosoftLearning/AI-102-AIEngineer#189]
# Module: 04 Building Speech-Enabled Applications https://microsoftlearning.github.io/AI-102-AIEngineer/Instructions/07-speech.html 
#### Step: 02 - Python

Description of issue:
Running the command with version reference returns an error:
"AI-102-AIEngineer-5\07-speech\Python\speaking-clock> pip install azure-cognitiveservices-speech==1.19.0
ERROR: Could not find a version that satisfies the requirement azure-cognitiveservices-speech==1.19.0 (from versions: 1.20.0, 1.21.0, 1.22.0, 1.23.0, 1.24.0, 1.24.1, 1.24.2, 1.25.0, 1.25.1b1, 1.26.0, 1.27.0, 1.28.0)
ERROR: No matching distribution found for azure-cognitiveservices-speech==1.19.0"

Solution: Run the command without version reference and upgrade if needed: 
"pip install azure-cognitiveservices-speech"
"pip install --upgrade azure-cognitiveservices-speech"

Current version: azure-cognitiveservices-speech 1.28.0

Link reference: https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstarts/setup-platform?pivots=programming-language-python&tabs=windows%2Cubuntu%2Cdotnet%2Cjre%2Cmaven%2Cnodejs%2Cmac%2Cpypi

Repro steps:
Python 3.10.10, VScode
1. Follow lab "Recognize and Synthesize Speech" steps, task "Prepare to use the Speech service" step 2.

**Comment by ivorb** [comment]
addressed by #191
