### ISSUE TITLE
LAB 05-b: Language Understanding API Version retired

### ISSUE THREAD

**Issue by massimobonanni** [MicrosoftLearning/AI-102-AIEngineer#196]
# Module: 05
#### Step: 04

Description of issue
The lab code uses the .NET package `Azure.AI.Language.Conversations` version `1.0.0-beta.2` and seems that this package use the Language Understanding `2021-11-01-preview` API version.
When the students run the .NET application and try to invoke the LU model, they receive the following error:

![image](https://github.com/MicrosoftLearning/AI-102-AIEngineer/assets/9560142/ce29a60f-8270-4438-8fbb-b75bdf702571)

The solution may be to update the `Azure.AI.Language.Conversations` package to the `1.0.0` or `1.1.0` version but, in that case, the SDK has different classes to manage the interaction with the Language Understanding service according to the official documentation [here](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/ai.language.conversations-readme?view=azure-dotnet).
The code in the lab must be change.

**Comment by ivorb** [comment]
This has been addressed with most recent commit, thanks for reporting!
