### ISSUE TITLE
Microsoft Azure Sponsorship Pass does not have microsoft.insights registered by default

### ISSUE THREAD

**Issue by davecatt** [MicrosoftLearning/AI-102-AIEngineer#2]
# Module: 00
#### Step: 4

Description of issue
When creating an alert for cognitive services, the microsoft.insights resource provider is not registered by default.  It was possible to register this through the portal however so perhaps a case of just adding an instruction.

Repro steps:

1.Select an cognitive services resource
1. Click Alerts in the blade menu
1. Notice that you cannot create an alert condition

**Comment by GraemeMalcolm** [comment]
I added steps to check its status (and register if necessary)
