### ISSUE TITLE
Bot composer improvment

### ISSUE THREAD

**Issue by true-while** [MicrosoftLearning/AI-102-AIEngineer#20]
# Lab 14

## Description of issue

The bot is caching ZIP code entered for the first time and provides the same weather forecast even if you ask "weather" again.

## Repro steps:
- provide recommended instruction ZIP code.
- ask bot "weather" to enter in the dialog again.
- bot return weather for previous ZIP code.

## Fix
The simple fix is push back the "Delete property" with "user.zipcode" after the IF/ELSE action.  No extra step is required.

**Comment by GraemeMalcolm** [comment]
Already added as optional challenge - but we may need to trim this lab anyway
