### ISSUE TITLE
pip install azure-ai-textanalytics=5.3.0  works not 5.1.0

### ISSUE THREAD

**Issue by prabhjotsinghbakshi** [MicrosoftLearning/AI-102-AIEngineer#200]
for the labs
01-get-started-cognitive-services.md
02-cognitive-services-security.md
Use 
pip install azure-ai-textanalytics==5.3.0
Not
pip install azure-ai-textanalytics==5.1.0

**Comment by ivorb** [comment]
thanks for reporting @prabhjotsinghbakshi this will be fixed with an incoming commit
