### ISSUE TITLE
Container lab does not work

### ISSUE THREAD

**Issue by sayedimac** [MicrosoftLearning/AI-102-AIEngineer#202]
# Module: 04
#### Step: 00

Description of issue
I have deployed this now about 8 times with ACI as instructed (key, URL, all of it - same port, etc.). This does not work. Get errors on the ACI instance. SO eventually I cannot execute the CURL command successfully. I managed to deploy to local Docker desktop, but not to ACI

Repro steps:
Just follow the lab steps

**Comment by ivorb** [comment]
dupe of #187
