### ISSUE TITLE
Issue on Get Started with Cognitive Services 

### ISSUE THREAD

**Issue by SDSTony** [MicrosoftLearning/AI-102-AIEngineer#203]
# Module: 01
#### Step: Description paragraph for the task

Description of issue
If we follow the steps on Lab 1 Task 1, it will create a general Cognitive Service resource. However, on the description for Task 1, it says we will be using a single (individual) Cognitive Service resource for this lab. So the description is not matching with the steps for Task 1. 

I believe the description can be more clear if we change it to `In this case, you’ll provision a general Cognitive Services resource.`

Repro steps: 
![image](https://github.com/MicrosoftLearning/AI-102-AIEngineer/assets/46511987/dd7a9c73-7149-40aa-ae83-0ff3f605f4de)

**Comment by Mihai-Ac** [comment]
Thank you @SDSTony 
Changes have been made to fix this incohrence.

**Comment by SDSTony** [comment]
Hello @Mihai-Ac, you've edited the wrong word. Could you please check again?

**Comment by ivorb** [comment]
Hi @SDSTony, Mihai's edit is correct - it is a single resource that provides access to multiple cog services APIs. By clarifying the sentence he did, it then makes the following sentence you opened this issue on. I can make the resource more descriptive too, if that helps.

**Comment by SDSTony** [comment]
@ivorb Okay understood. On the previous version, I was mapping the term `single` to the term `individual`, (not `single` to `general`) so my intention was to change the `single` to `general` in the last sentence for a consistency in terms being used. 

But if we change the `general` to `single` on the second sentence, then the last sentence makes sense as well by staying in `single`, so I believe that will be fine as well. 

Thank you team for the fix.
