### ISSUE TITLE
HTML rendering breaks markdown and makes notes hard to work with

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/AI-102-AIEngineer#208]
# Module: 02
#### Step: 03

Description of issue
The rendering of notes and tables with code snippets is different in markdown and html on GitHub. The html version is not legible and hard to work with. Not sure what causes this, but it should be corrected so that it looks like in markdown. This is just one example, but the same rendering issue exists in several other labs.

Markdown:
https://github.com/MicrosoftLearning/AI-102-AIEngineer/blob/master/Instructions/04-use-a-container.md
<img width="804" alt="image" src="https://github.com/MicrosoftLearning/AI-102-AIEngineer/assets/37703728/129af32d-3784-4c5d-9cc2-7ecd7f20dbff">

Html:
https://microsoftlearning.github.io/AI-102-AIEngineer/Instructions/04-use-a-container.html
<img width="760" alt="image" src="https://github.com/MicrosoftLearning/AI-102-AIEngineer/assets/37703728/80222316-c2c0-421e-947e-db4b6cef9f8d">

**Comment by ivorb** [comment]
fixed with update today
