### ISSUE TITLE
Missing Instruction for type of Azure AI Service resources to create

### ISSUE THREAD

**Issue by VincentK16** [MicrosoftLearning/AI-102-AIEngineer#211]
For Lab 15-Analyze Images with Azure AI Vision and Lab 19-Detect and Analyze Faces, the below instructions need to be improved:

Initial instructions:
In the top search bar, search for Azure AI services, select Azure AI Services, and create a resource with the following settings:
- Subscription: Your Azure subscription
- Resource group: Choose or create a resource group (if you are using a restricted subscription, you may not have permission to create a new resource group - use the one provided)
- Region: Choose any available region
- Name: Enter a unique name
- Pricing tier: Standard S0

Suggested instructions:
In the top search bar, search for Azure AI services, select Azure AI Services, and **create an Azure AI services multi-service account** resource with the following settings:
- Subscription: Your Azure subscription
- Resource group: Choose or create a resource group (if you are using a restricted subscription, you may not have permission to create a new resource group - use the one provided)
- Region: Choose any available region
- Name: Enter a unique name
- Pricing tier: Standard S0

This will give a better clarity for learners to create a multiple-service account for Azure AI services. 

Thanks!

**Comment by ivorb** [comment]
fixed with 584cb6b
