### ISSUE TITLE
EndPoints

### ISSUE THREAD

**Issue by ahsan296** [MicrosoftLearning/AI-102-AIEngineer#213]
# Module: Ai-102 Module 12

Description of issue
When I perform this task in this lab In the Margie's Travel website, enter London hotel into the search box and click Search.
Its shows the endpoint error that screen shot attach below but when I check at search resource keys section in this section only contains 2 admin keys and 1 query key not endpoints why?

![image](https://github.com/MicrosoftLearning/AI-102-AIEngineer/assets/142339674/eb7c9fce-17ff-4e6a-942f-ebcf0e9de81b)

**Comment by ivorb** [comment]
This worked fine for me, can you confirm you can query the index from the Azure portal, and that the webapp is running when you try to reach that endpoint? I'm also unclear what you mean with the search resource keys section, if you could please elaborate

**Comment by ahsan296** [comment]
> This worked fine for me, can you confirm you can query the index from the Azure portal, and that the webapp is running when you try to reach that endpoint? I'm also unclear what you mean with the search resource keys section, if you could please elaborate

![image](https://github.com/MicrosoftLearning/AI-102-AIEngineer/assets/142339674/611180fd-8d21-4374-99fd-b11b98ea4507)
When I reach this point and try to search, I receive the same error as shown in the picture you sent above, even though all the preceding steps are performed correctly. If you have a screenshot of this issue, please share it with me.

**Comment by ahsan296** [comment]
> > This worked fine for me, can you confirm you can query the index from the Azure portal, and that the webapp is running when you try to reach that endpoint? I'm also unclear what you mean with the search resource keys section, if you could please elaborate
> 
> ![image](https://user-images.githubusercontent.com/142339674/264652650-611180fd-8d21-4374-99fd-b11b98ea4507.png) When I reach this point and try to search, I receive the same error as shown in the picture you sent above, even though all the preceding steps are performed correctly. If you have a screenshot of this issue, please share it with me.

Webapp is running but when we search query in search bar then its give this error.

**Comment by ivorb** [comment]
I'll have to see if I can replicate your error to figure out what went wrong.

**Comment by ahsan296** [comment]
> I'll have to see if I can replicate your error to figure out what went wrong. I'll circle back if I can find how to solve your problem.

Ok thank you @ivorb for contributing.

**Comment by ivorb** [comment]
I unfortunately cannot reproduce this error when following the lab, and the lab will be getting updates shortly. Please open an issue if you continue to have problems
