### ISSUE TITLE
# Module: Use an Azure AI Service Container ( error with LOD- learn on demand env)

### ISSUE THREAD

**Issue by prabhjotsinghbakshi** [MicrosoftLearning/AI-102-AIEngineer#214]
# Module: Use an Azure AI Service Container ( error with LOD- learn on demand)
IF using LOD env,  then The error of Policy voilation for  12 GB ram Container ( may be only 4 GB allowed) in that case the old Container image will work -( with 4 GB ram) 
mcr.microsoft.com/azure-cognitive-services/textanalytics/language:1.1.013570001-amd64

else the Lab work Fine with your Pay as you go - Subscription

**Comment by ivorb** [comment]
Skillable reports this being fixed late yesterday.
