### ISSUE TITLE
22-Create-a-search-solution - Uploading Data to Storage issue

### ISSUE THREAD

**Issue by prabhjotsinghbakshi** [MicrosoftLearning/AI-102-AIEngineer#215]
22-Create-a-search-solution
##Step - Upload Documents to Azure Storage
### Task 1- In Visual Studio Code, in the Explorer pane, expand the 22-create-a-search-solution folder and select UploadDocs.cmd.
ERROR on this Step -
5- Enter the following command to run the batch file. This will create a blob container in your storage account and upload the documents in the data folder to it.

UploadDocs

![image](https://github.com/MicrosoftLearning/AI-102-AIEngineer/assets/12583943/8711e219-dfff-4e2c-b956-89025beda26d)

Solution -
Go to Azure Stiorage Acccount - Configuration -  Allow Blob anonymous access= Enable and then run the command from VS code again it work 

![image](https://github.com/MicrosoftLearning/AI-102-AIEngineer/assets/12583943/0388e7ec-fac1-4fa0-bce9-b3ec73f0fd39)

**Comment by ivorb** [comment]
fixed with 8cc834d. Thanks for reporting!
