### ISSUE TITLE
[CloudSlice] Container lab, only 4 GiB memory can be used for Container Instance

### ISSUE THREAD

**Issue by msftnutta** [MicrosoftLearning/AI-102-AIEngineer#216]
# Module: 4

Description of issue

Repro steps:

1. Creating the container instance by using 1 vCPU and 12 GiB memory.
1. Error as CloudSlice does not allow 12 GiB of memory, only 4 GiB allowed.

![ai-102-container-lab](https://github.com/MicrosoftLearning/AI-102-AIEngineer/assets/98095529/4cc9665e-78f8-4cf8-8fa8-a600b82c1533)

I've submitted the ticket directly to Skillable and will update this issue if I get any updates from them.

**Comment by ivorb** [comment]
Reached out to skillable myself on this too

**Comment by ivorb** [comment]
Skillable reports this being fixed late yesterday.

**Comment by msftnutta** [comment]
verified and it's working with ACI + 12 GiB of memory
