### ISSUE TITLE
Firewall issues

### ISSUE THREAD

**Issue by true-while** [MicrosoftLearning/AI-102-AIEngineer#22]
#### Step: 1

**Description of issue**
Starting bot hangs. Suppose to ask about firewall issues but does not. Just spin for 5-10 min without any result.
Restarting bot emulator not able to start a second bot because of the error about concurrent access. After killing all processes responsible for bot run next run return firewall request and then start successful.

**Fix**
Updating instruction or set up firewall on LOD image by clicking button run in composer.

**Comment by GraemeMalcolm** [comment]
VM updated
