### ISSUE TITLE
Python Packages in 15 Computer Vision

### ISSUE THREAD

**Issue by mirontoli** [MicrosoftLearning/AI-102-AIEngineer#220]
# Module: 15 Computer Vision
#### Step: prepare-to-use-the-azure-ai-vision-sdk

Description of issue: Missing python packages

Add the following packages too:

```bash
pip install matplotlib
pip install Pillow
```

Also remove or uncomment unused import in `image-analysis.py`

```python
import numpy as np
```

Repro steps:

1.
1.
1.

**Comment by ivorb** [comment]
I'm in the process of refreshing this lab and content, I'll address these at the same time. Thanks for reporting!

**Comment by mirontoli** [comment]
Thank you!
