### ISSUE TITLE
Typo in 10b-clu-client-(preview)/Python/clock-client/clock-client.py

### ISSUE THREAD

**Issue by SDSTony** [MicrosoftLearning/AI-102-AIEngineer#226]
Description of issue
In the `10b-clu-client-(preview)/Python/clock-client/clock-client.py` file, there is a typo when defining the `GetDate()` function. 

![image](https://github.com/MicrosoftLearning/AI-102-AIEngineer/assets/46511987/c3e94a56-67ff-4566-a411-dc19a9c68368)

`thusday` needs to be `thursday`.

**Comment by Mihai-Ac** [comment]
Issue sovled with PR #227
