### ISSUE TITLE
Lab 5: git clone repo and destination folder appear incorrect

### ISSUE THREAD

**Issue by SkillableMG** [MicrosoftLearning/AI-102-AIEngineer#228]
- Module 3 - Getting Started with Natural Language Processing
- Lab 5: Analyze Text
- Task: Clone the repository for this course in Cloud Shell
- step 5

In the above-referenced step, a repository is cloned into a different destination folder than is mentioned elsewhere in the task. The repository does not contain the indicated `05-analyze-code` folder. Substituting the following alternate clone command allowed the lab to be completed in our testing:

```bash
git clone https://github.com/MicrosoftLearning/AI-102-AIEngineer.git azure-ai-eng
```

https://github.com/MicrosoftLearning/AI-102-AIEngineer/blob/2905b86add31ad489d919abbaab06511f757430d/Instructions/05-analyze-text.md?plain=1#L44-L55

**Comment by ivorb** [comment]
@SkillableMG thanks for pointing this out! fixed just now with abb18f4
