### ISSUE TITLE
Build ZIP package for deployment

### ISSUE THREAD

**Issue by true-while** [MicrosoftLearning/AI-102-AIEngineer#23]
#### Step: 2

Description of issue
package for deployment should be prepared by command detent publish and zipping output folder.
it is different from python.

https://docs.microsoft.com/en-us/azure/app-service/deploy-zip#create-a-project-zip-file

"_For **dotnet** projects, this folder is the output folder of the **dotnet publish** command._"

**Comment by GraemeMalcolm** [comment]
The product documentation is to zip the root folder containing the .csproj file
