### ISSUE TITLE
Face properties age and emotions are not detected in the current version, text needs to be updated

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/AI-102-AIEngineer#233]
# Module: 10
#### Step: "5" (numbering is broken)

Description of issue
The code was changed a while ago to remove limited access properties from the analysis but the text in the lab doesn't reflect this.

Now:
Examine the code you added to the DetectFaces function. It analyzes an image file and detects any faces it contains, including attributes for **age, emotions,** and the presence of spectacles. The details of each face are displayed, including a unique face identifier that is assigned to each face; and the location of the faces is indicated on the image using a bounding box.

Should be:
Examine the code you added to the DetectFaces function. It analyzes an image file and detects any faces it contains, including attributes for occlusion, blur, and the presence of spectacles. The details of each face are displayed, including a unique face identifier that is assigned to each face; and the location of the faces is indicated on the image using a bounding box.

**Comment by ivorb** [comment]
fixed with 5a880db
