### ISSUE TITLE
Editor choice as cloud shell not practical and not user friendly

### ISSUE THREAD

**Issue by azurearchitect786** [MicrosoftLearning/AI-102-AIEngineer#234]
Lab/Demo: 06 Translate Text

Description of issue: Why have we unnecessarily asked learners to use the cloud shell editor instead of VS code. Majority of the participants faced issue in the cloud shell editor.

**Comment by julians1966** [comment]
Seconded, Lab 6 Analyze text and Lab 7 Translate text using Visual Code online caused serious problems for every student
It must be changed to use Visual Studio Code 
Copy and pasting code is difficult and introduces errors, the folder names are not correct, students are not told to change to the correct directory
Also copying and pasting code does not add any value

**Comment by GraemeMalcolm** [comment]
Thanks for the feedback. We're exploring various options to ensure a consistent experience across self-paced learners on Microsoft Learn and ILT learners. To support VS Code in a VM, we need to maintain 2 versions of every lab profile (one for Learn, one for ILT); and as the curriculum grows and we need to update the installed tools and frameworks on the client, it presents challenges to scalability maintenance overhead. Cloud shell offers us an alternative, lower overhead way to provide a hands-on experience.

We do appreciate the feedback, and we'll take it into consideration as we continue to evolve the lab strategy.
