### ISSUE TITLE
Lab 16 Video Indexer Screenshots

### ISSUE THREAD

**Issue by VincentK16** [MicrosoftLearning/AI-102-AIEngineer#236]
# Module: 8 Computer Vision
#### Step: [Review video insights](https://github.com/MicrosoftLearning/AI-102-AIEngineer/blob/master/Instructions/16-video-indexer.md#review-video-insights)

Description of issue
While the lab instructions show the screenshot where they detected 25 people and also with the recognized people name in the video, when the learners and myself tried out, it only shows 2 people and Unknown #1 and Unknown #2. 

This is what I see when using the Responsible AI video: 
<img width="897" alt="image" src="https://github.com/MicrosoftLearning/AI-102-AIEngineer/assets/3338753/40c876b4-0af9-4dcc-9b40-2821e3624481">

Is there a reason for that? Free account vs unlimited account?

Thanks!

Repro steps:

1.
1.
1.

**Comment by GraemeMalcolm** [comment]
There may be restrictions for some accounts, and it's possible the model has changed since the screenshots were taken.
