### ISSUE TITLE
Form Recognizer lab - error creating container in storage account

### ISSUE THREAD

**Issue by julians1966** [MicrosoftLearning/AI-102-AIEngineer#237]
#### Step: 13

Description of issue

The setup.cmd fails to create the sample-forms container in the blob storage account due to a policy preventing public container and files fail to be uploaded.

To resolved edit the setup.cmd file and remove "--public-access blob" from az container create line 27

Repro steps:

1. Run setup.cmd on ALH lab

**Comment by GraemeMalcolm** [comment]
@LODS-41-319, is this down to a policy in the cloud slice?

**Comment by julians1966** [comment]
Looks like a policy on cloud slice
But there is no need for the container to be public, the labs works if you remove public access as it generates a SAS key for the container

**Comment by GraemeMalcolm** [comment]
Fixed. Thanks for raising this @julians1966
