### ISSUE TITLE
Iteration invalid in 18-object-detection

### ISSUE THREAD

**Issue by VishwamurthySangam** [MicrosoftLearning/AI-102-AIEngineer#238]
# Module: 18-object-detection
#### Step: 5

Description of issue
In both 17-image-classification and 18-object-detection the results are captured like so:
results = prediction_client.classify_image(project_id, model_name, image_data)
results = prediction_client.detect_image(project_id, model_name, image_data)

I had to modify them as below to get them to test the image classifier or image detector program
results = prediction_client.classify_image(project_id, "Iteration2", image_data)
results = prediction_client.detect_image(project_id, "Iteration1", image_data)

Repro steps:

1. Provide all the necessary details on Prediction API in the Environment file
2. Run the program
3. Output: Error: Invalid Iteration. Instead of the Model Name, the function is using the Iteration Name
4. I'm running the Python program. Not sure if this is applicable for the C# program too.

**Comment by GraemeMalcolm** [comment]
Looks like you missed the instruction to change the model name when publishing the trained model
