### ISSUE TITLE
Registering Providers for Azure Pass

### ISSUE THREAD

**Issue by true-while** [MicrosoftLearning/AI-102-AIEngineer#24]
### Description of issue

Registration following providers upfront of the labs should help to avoid provisioning issues 

- Microsoft.insights
- Microsoft.BotSerice
- Microsoft.Search

The following command can automate the process. 

**az provider register --namespace 'Microsoft.Insights'**

https://docs.microsoft.com/en-us/cli/azure/provider?view=azure-cli-latest#az_provider_register-examples

**Comment by GraemeMalcolm** [comment]
This seems to be an issue with the Azure pass subscription, not the content. As such, I've raised it with the VM team so they can follow-up with the Azure Pass team to resolve it. In the meantime, I've added procedures to enable the resource providers in each lab where we experience the issue.
