### ISSUE TITLE
lab 23 custom skill has issue in the setup file.

### ISSUE THREAD

**Issue by true-while** [MicrosoftLearning/AI-102-AIEngineer#243]
## Lab 23

Description of issue
storage account is not allowed public accessed containers any more. you have to do that explicitly. The command **az strorage create** should  include parameter **--allow-blob-public-access**

Please fix the script

Repro steps:
run script you got error that container not found. 
![Screenshot 2023-11-02 150715](https://github.com/MicrosoftLearning/AI-102-AIEngineer/assets/25492227/d688fbc1-ab00-4ad2-a488-03093edf636c)

**Comment by GraemeMalcolm** [comment]
Fixed
