### ISSUE TITLE
Lab 22 Create an Azure Cognitive Search solution UploadDocs.cmd error

### ISSUE THREAD

**Issue by SDSTony** [MicrosoftLearning/AI-102-AIEngineer#246]
As in accordance with [this update](https://github.com/MicrosoftLearning/AI-102-AIEngineer/commit/4354e1e6787780ad68be804cee13e6d6e82101f0), the UploadDocs.cmd script needs to be updated as well to remove the public blob access parameter.

If it's not removed, the script will return an error. 
![image](https://github.com/MicrosoftLearning/AI-102-AIEngineer/assets/46511987/bfdc78e4-dcb6-40ad-9699-224207454c20)

**Comment by GraemeMalcolm** [comment]
Fixed - thanks
