### ISSUE TITLE
'tell me about certification' - do not return expected result

### ISSUE THREAD

**Issue by true-while** [MicrosoftLearning/AI-102-AIEngineer#25]
#### Step: 6

**Description of issue**
The request "tell me about certification" returns more than one result and expected result is not returned.

**Repro steps:**
When testing from LUIS portal type "tell me about certification". Two results will be returned : 
"you can tell where you are... "

![image](https://user-images.githubusercontent.com/25492227/106323819-0a00f600-6246-11eb-9ddd-05466d830aef.png)

**Comment by GraemeMalcolm** [comment]
Not repro for me I'm afraid.
