### ISSUE TITLE
AI-102 - Lab 7 - Incorrect key/region variable names for SpeechConfig in C# 

### ISSUE THREAD

**Issue by AndyLi-Vitals** [MicrosoftLearning/AI-102-AIEngineer#251]
# Module: Module 4 - Create speech-enabled apps with Azure AI services
### Description of issue
In C#, the following error is observed on line 26 of the Program.cs file:

> The name 'cogSvcKey' does not exist in the current context

In the instructions file, the following change needs to be made. 
From:
`
// Configure speech service
speechConfig = SpeechConfig.FromSubscription(cogSvcKey, cogSvcRegion);
`
to:
`
// Configure speech service
speechConfig = SpeechConfig.FromSubscription(aiSvcKey, aiSvcRegion);
`

Please kindly also review the Python variant of this lab.

**Comment by GraemeMalcolm** [comment]
Note that the files for this lab have been moved to https://github.com/MicrosoftLearning/mslearn-ai-language/blob/main/Instructions/Exercises/07-speech.md. This repo is being deprecated.
