### ISSUE TITLE
Capture Error on last step when searching 'London Hotel'

### ISSUE THREAD

**Issue by janeroughan** [MicrosoftLearning/AI-102-AIEngineer#28]
# Module: 00
#### Step: 01

Description of issue
Running http://localhost:5000/, when I search London Hotel, I get the following error, I must have done something wrong. PS I am using Python.
![image](https://user-images.githubusercontent.com/24537110/106550683-bbb26680-6567-11eb-8758-0aa2f05a4870.png)

NOTE: I stopped that this step and did not continue to lab 23 and 24, so I don't blow the Lab away.

Repro steps:

1.
1.
1.

**Comment by GraemeMalcolm** [comment]
Non-repro - looks like you may have mistyped your search URL in the settings file
