### ISSUE TITLE
The .env for the python code repeats your_service_principle_tenant_id

### ISSUE THREAD

**Issue by davecatt** [MicrosoftLearning/AI-102-AIEngineer#3]
# Module: 00
#### Step: 3

Description of issue
The .env for the python code repeats your_service_principle_tenant_id where it should be specific, i.e. YOUR_SERVICE_PRINCIPAL_APP_ID, YOUR_SERVICE_PRINCIPAL_PASSWORD

Repro steps:

1.
1.
1.

**Comment by GraemeMalcolm** [comment]
Good catch! Updated to match C# version
