### ISSUE TITLE
lab 13 - Suggest placeholders for recourses when deploying bot

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/AI-102-AIEngineer#51]
# Module: 07
#### Step: 00

Description of issue
Please suggest names for placeholder. Student facing too much problems when deploying the bot in a single line.
This is too vague: "The resource IDs you specify must be globally unique strings netween 4 and 42 characters long. "
Also mention that the BotId is the name of the bot

resource-group=ai102timebotrg
botId=ai102timebot<yourname>
newAppServicePlanName=BotServicePlan
newWebAppName = ai102timebot<yourname>
appScecret = thesecretpassword
name = BotDeployment

And afterwards, after spending too much time correcting the command, the bot is not working in Azure.

Repro steps:

az deployment group create --resource-group "YOUR_RESOURCE_GROUP" --template-file "deploymenttemplates/template-with-preexisting-rg.json" --parameters appId="YOUR_APP_ID" appSecret="Super$ecretPassw0rd" botId="A_UNIQUE_BOT_ID" newWebAppName="A_UNIQUE_WEB_APP_NAME" newAppServicePlanName="A_UNIQUE_PLAN_NAME" appServicePlanLocation="REGION" --name "A_UNIQUE_SERVICE_NAME"
1.
1.
1.

**Comment by GraemeMalcolm** [comment]
The instructions are correct as-is - we can't suggest names for the placeholders because, as the instructions say, they must be globally unique.
