### ISSUE TITLE
Please use another AD App password, gives errors in PowerShell 

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/AI-102-AIEngineer#52]
# Module: 07
#### Step: 00

Description of issue
az ad app create --display-name "TimeBot" --password "Super$ecretPassw0rd" --available-to-other-tenants

Please don't use "Super$ecretPass0rd". When student use powershell in Visual Studio code, or just PowerShell, Powershell doesn't like $ character in double quote string.

It give strange behaviour when deploying the timebot
az deployment group create --resource-group "YOUR_RESOURCE_GROUP" --template-file "deploymenttemplates/template-with-preexisting-rg.json" --parameters appId="YOUR_APP_ID" appSecret="Super$ecretPassw0rd" botId="A_UNIQUE_BOT_ID" newWebAppName="A_UNIQUE_WEB_APP_NAME" newAppServicePlanName="A_UNIQUE_PLAN_NAME" appServicePlanLocation="REGION" --name "A_UNIQUE_SERVICE_NAME"

I have replaced double quotes into single quotes, but that ended up with single quotes in the Web App configuration.

My suggestion: replace $ with 5
--password "Super$ecretPassw0rd"  -> --password "Super5ecretPassw0rd"

Repro steps:

1. Visual studio code with PowerShell terminal
1. PowerShell
1.

**Comment by GraemeMalcolm** [comment]
Lab instructions are to do this using the CLI, not PowerShell. If you use PowerShell, you'll need to escape the reserved $ character.
