### ISSUE TITLE
Framework Composer dotnet build fails with .net 5.0 only?

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/AI-102-AIEngineer#53]
# Module: 07
#### Step: 00

Description of issue
Student is facing dotnet build errors in Framework Composer like: https://github.com/microsoft/BotFramework-Composer/issues/4812
In this issue someone suggested: "
I had to uninstall .Net 5, reboot and install to .Net 3.41
…"

The setup instruction says:  "NET Core SDK
Download and install from https://dotnet.microsoft.com/download (download .NET Core SDK - not just the runtime)" 
 
Student has installed everything on his local computer: just .Net 5.0 SDK.  He didn't install 3.1.

On my machine, I have 3.1 and 5.0 and everything works. 

Repro steps:

1. Bot Framework Composer 1.3.1 (latest version)
2. .NET SDK 5.0
1.
1.

**Comment by GraemeMalcolm** [comment]
.NET SDK 5.0 is not the same as .NET Core SDK.
The labs are designed to be completed in the provided hosted environment, which includes all the necessary prerequisite software.
You can use your own environment if you wish, but it's at your own risk - we can't provide support for it - sorry!

**Comment by molenaar** [comment]
Latest version of .NET Core is 5.0.
https://dotnet.microsoft.com/download/dotnet/5.0

![image](https://user-images.githubusercontent.com/10166617/109998256-5641c900-7d11-11eb-9f73-8dca2886cca1.png)

Sorry to hear there is no support for MCTs encouraging their student the recommended version of .NET core.

https://docs.microsoft.com/en-us/dotnet/core/dotnet-five

> .NET 5.0 is the next major release of .NET Core following 3.1. We named this new release .NET 5.0 instead of .NET Core 4.0 for two reasons:

We skipped version numbers 4.x to avoid confusion with .NET Framework 4.x.
We dropped "Core" from the name to emphasize that this is the main implementation of .NET going forward. .NET 5.0 supports more types of apps and more platforms than .NET Core or .NET Framework.
ASP.NET Core 5.0 is based on .NET 5.0 but retains the name "Core" to avoid confusing it with ASP.NET MVC 5. Likewise, Entity Framework Core 5.0 retains the name "Core" to avoid confusing it with Entity Framework 5 and 6.


Perhaps you can modify the instructions to .NET Core 3.1 SDK instead of the latest.....

**Comment by GraemeMalcolm** [comment]
We're pinned to the version in the VM - we will update as we refresh the course in future, but for now we recommend you use the hosted lab environment provded.
