### ISSUE TITLE
Double bytes character handling issue

### ISSUE THREAD

**Issue by yunkyoungaum** [MicrosoftLearning/AI-102-AIEngineer#56]
# Module: 02
#### Step: 00

Description of issue

Console app can not handle  2 bytes input like Korean,Japanese etc
Please consider this

one idea is adding unicode encoding to console.

                Console.InputEncoding = Encoding.Unicode;
                Console.OutputEncoding = Encoding.Unicode;

**Comment by GraemeMalcolm** [comment]
Investigating....

**Comment by GraemeMalcolm** [comment]
Fixed (also for module 1 labs)
