### ISSUE TITLE
Website changed for getting API details Video Indexer

### ISSUE THREAD

**Issue by madiepev** [MicrosoftLearning/AI-102-AIEngineer#60]
# Module: 08
#### Step: 04

Description of issue
Website changed. Instead of **Products** page and **Authorization** it is now under **Profile** and **Subscriptions**

**Comment by GraemeMalcolm** [comment]
I updated the insructions on the qssumption that at least one subscription is automatically created. The docs aren't updated yet, so it's difficult to tell what happens if not. LMK if you see any other changes in behavior.
