### ISSUE TITLE
Error when trying to run modify-search.cmd

### ISSUE THREAD

**Issue by Jordithecloud** [MicrosoftLearning/AI-102-AIEngineer#62]
# Module: 
#### Step: 
Description of issue

I tried to follow the steps in https://docs.microsoft.com/en-us/learn/modules/create-azure-cognitive-search-solution/8-exercise-search. I'm stuck at step "Use the REST API to update the search solution", when I run modify-search.cmd it fails with error: 

Updating the index...
{"error":{"code":"OperationNotAllowed","message":"Existing field 'language' cannot be changed.","details":[{"code":"CannotChangeExistingField","message":"Existing field 'language' cannot be changed."}]}}

and:

Updating the indexer...
{"error":{"code":"","message":"Output field mapping specifies target field 'sentiment' that doesn't exist in the index"}}-----

Please assist!

**Comment by GraemeMalcolm** [comment]
Non-repro for me I'm afraid @Jordithecloud .
The most likely cause is that when you originally created the index in the UI, you missed one of the attribute checkboxes for the **language** field (or checked an additional one). The **language** field should only be **retrievable** and **filterable**.

**Comment by Jordithecloud** [comment]
I checked the doc twice. What do you need from my side to reproduce?

**Comment by GraemeMalcolm** [comment]
Can you copy your index definition (JSON) from the portal UI and post the **language** element here?

**Comment by Jordithecloud** [comment]
@GraemeMalcolm, I feel so stupid. I indeed left the Searchable checkmark on. Thanks for the quick responses, it's working now.

**Comment by GraemeMalcolm** [comment]
No worries - it's an easy one to miss!
