### ISSUE TITLE
No code found

### ISSUE THREAD

**Issue by Jordithecloud** [MicrosoftLearning/AI-102-AIEngineer#63]
# Module: 00
#### Step: 00
It's me again, this time I noticed the below folder is empty. Empty as in, there is no code. I'm looking for Python code in particular.

https://github.com/MicrosoftLearning/AI-102-AIEngineer/tree/master/13-bot-framework

**Comment by GraemeMalcolm** [comment]
This is by-design - the [lab instructions](https://microsoftlearning.github.io/AI-102-AIEngineer/Instructions/13-bot-framework.html) have you create the bot from the Bot Framework SDK template
