### ISSUE TITLE
.cmd files can only be run on Windows machines

### ISSUE THREAD

**Issue by wilsonmar** [MicrosoftLearning/AI-102-AIEngineer#64]
The lone curl command in some of the rest-test.cmd files can still be used by students using MacOS or Linux by copying and pasting to a Terminal.

But the following command files can only be used by Windows users:

* https://github.com/MicrosoftLearning/AI-102-AIEngineer/blob/master/09-luis-app/GetIntent.cmd
* https://github.com/MicrosoftLearning/AI-102-AIEngineer/blob/master/21-custom-form/setup.cmd
* https://github.com/MicrosoftLearning/AI-102-AIEngineer/blob/master/22-Create-a-search-solution/UploadDocs.cmd
* https://github.com/MicrosoftLearning/AI-102-AIEngineer/blob/master/23-custom-search-skill/setup.cmd
* https://github.com/MicrosoftLearning/AI-102-AIEngineer/blob/master/24-knowledge-store/setup.cmd

This has huge implications. 
First of all, the course description should disclose this limitation at 
https://docs.microsoft.com/en-us/learn/certifications/courses/ai-102t00
In the Prerequisites.

Just as there are both C# and Python, will there be both .cmd and bash shell scripts?
Perhaps as student contributions?

**Comment by GraemeMalcolm** [comment]
The labs are designed to be run in the hosted l;ab environment.
