### ISSUE TITLE
rest-test.cmd host name changed

### ISSUE THREAD

**Issue by wilsonmar** [MicrosoftLearning/AI-102-AIEngineer#66]
Running https://github.com/MicrosoftLearning/AI-102-AIEngineer/blob/master/02-cognitive-security/rest-test.cmd
I get error "Couldn't resolve host '...cognitiveservices.azure.com'
until I changed the host name to what appears in the Portal:
https://westus.api.cognitive.microsoft.com

Then I get correct response to userText input "hola":
{"documents":[{"id":"1","detectedLanguage":{"name":"Spanish","iso6391Name":"es","confidenceScore":1.0},"warnings":[]}],"errors":[],"modelVersion":"2021-01-05"}

**Comment by GraemeMalcolm** [comment]
The lab instructions tell you to change the endpoint to your endpoint.
