### ISSUE TITLE
Requirements.txt File for Python Labs

### ISSUE THREAD

**Issue by zzenonn** [MicrosoftLearning/AI-102-AIEngineer#67]
# Module: ALL
#### Step: ALL

Description of issue

**Feature Request:** Would it be possible to include a requirements.txt file for the Python labs? Some learners don't like using the lab environment VM, and want to run the samples from their own machines.

**Comment by GraemeMalcolm** [comment]
Instructions to set up your own environment are at https://microsoftlearning.github.io/AI-102-AIEngineer/Instructions/00-setup.html. Note that we can't provide support for issues encountered in your own environment, and some scripts may not run in a non-Windows OS.
