### ISSUE TITLE
An "internal error" while trying to train the Form Recognizer model

### ISSUE THREAD

**Issue by houbena** [MicrosoftLearning/AI-102-AIEngineer#69]
# Module: 11
#### Step: 4

Description of issue
After running "dotnet run" for training, following error occurs:
![image](https://user-images.githubusercontent.com/8375842/121527305-8c6ea300-c9fa-11eb-8d51-3224b06f2a80.png)

Repro steps:
Following the instructions.
Many attendees raised the issue.

**Comment by sherzyang** [comment]
@houbena thanks for letting us know, I am looking into the issue.

**Comment by GraemeMalcolm** [comment]
The issue has been reported outside of this course, so it may not be a problem with the lab content/code.
https://docs.microsoft.com/en-us/answers/questions/428838/error-while-training-custom-form-recognizer.html

**Comment by GraemeMalcolm** [comment]
This issue has now been resolved by the Form Recognizer product team
