### ISSUE TITLE
Issue with Azure Cognitive Search

### ISSUE THREAD

**Issue by nish112** [MicrosoftLearning/AI-102-AIEngineer#70]
# Module: 12
#### Step: 02 (In Search explorer, in the Query string box, enter the following query string, and then select Search.)

Description of issue 
When clicking on the search resource to view 'Search Explorer' , getting error 'Authorization failed. Authentication token failed validation'

Repro steps:

1. run 'create-search.cmd'
2. Go to search resource in azure portal and go to search explorer and search a query
![issue](https://user-images.githubusercontent.com/26849166/122434096-6cb81b80-cfb4-11eb-9937-99a7e264cbd5.jpg)

To solve this i tried assigning owner role / Search Index Data Reader/ Search Index Data Contributor roles to the resource/ subscription but all in vain.

**Comment by GraemeMalcolm** [comment]
I've reproduced the issue - looks like an issue with either the VM networking or Azure itself rather than the lab instructions. After retrying the **Import data** link a few times it eventually worked.

**Comment by GraemeMalcolm** [comment]
Seems to be resolved now.
