### ISSUE TITLE
Fragile key hacking in cmd scripts. For example, lab 24

### ISSUE THREAD

**Issue by JonasMikaelMellin** [MicrosoftLearning/AI-102-AIEngineer#71]
In, for example, __https://github.com/MicrosoftLearning/AI-102-AIEngineer/blob/master/24-knowledge-store/setup.cmd__

you have 
rem Hack to get storage key
for /f "tokens=*" %%a in ( 
'az storage account keys list --subscription !subscription_id! --resource-group !resource_group! --account-name ai102str!unique_id! --query "[?keyName=='key1']"' 
) do ( 
set key_json=!key_json!%%a 
) 
set key_string=!key_json:[ { "keyName": "key1", "permissions": "Full", "value": "=!
set AZURE_STORAGE_KEY=!key_string:" } ]=!

the problem is that it is fragile. The JSON object returned by the query also includes a field "creationTime" and it makes this
fragile key hack to fail. I got the error message:
_unrecognized arguments: { creationTime: 2021-06-23T08:08:16.727815+00:00, keyName: key1, permissions: FULL, value: 0IY+kRl4n6wPdPntEd2Hdtx9AoKKQzYoXxhn5mZdNEJ9sJ+fWwsJ9Aohv3ltCioiO+gGnbH6LBtKp7wpFqMRgA==   --output none_

# Potential solution (out of many solutions):
The solution I added was to select the fields explicitly in the query. That is, replacing
 "[?keyName=='key1']"

with 
 "[?keyName=='key1'].{keyName:keyName, permissions:permissions, value:value}"

The whole thing can be simplified by, for example, only selecting "value:value", but then you need to change the script accordingly.

**Comment by GraemeMalcolm** [comment]
Thanks for the feedback. I'll work through the lab today and see if we can tighten it up a little.

**Comment by JonasMikaelMellin** [comment]
Great. I also ended up with Python 3.9.5 och Python 3.8.5 (via miniconda)
on my machine. The path variable in the system (Windows 10) put Python
3.9.5. ahead of 3.8..5 when I used PowerShell, but not when I used the Cmd
(weird!). I have not double checked why this happened, if I did something
wrong or if there has been some update in the software that makes the
installation instructions incorrect. Anyway, it was slightly awkward.

Best/Jonas Mellin

Den mån 28 juni 2021 kl 17:50 skrev Graeme Malcolm ***@***.***

**Comment by GraemeMalcolm** [comment]
Thanks for the additional context.
We do optimize for the hosted lab environment, which I guess is why we haven't seen this issue raised before, but I'll see if there are some changes we can make to try to be more "universal"!

**Comment by GraemeMalcolm** [comment]
I've updated the three scripts that use the storage key hack to use the expanded query you suggested - thanks!

**Comment by JonasMikaelMellin** [comment]
Great. Glad to be of assistance. Hopefully others will have less problems...

Best/Jonas Mellin

Den tis 29 juni 2021 kl 00:41 skrev Graeme Malcolm ***@***.***
