### ISSUE TITLE
Setup.cmd has unrecognized arguments. 

### ISSUE THREAD

**Issue by ToshikazuOki** [MicrosoftLearning/AI-102-AIEngineer#75]
# Module: 11
#### Step: 13

When I run setup.cmd Iget the following error messges
![image](https://user-images.githubusercontent.com/53045107/125554822-3bd25d45-383d-49f1-b4f9-ec5f5f20c4f7.png)
azure-cli version:2.25.0 and 2.26.0

**Comment by GraemeMalcolm** [comment]
Hi @ToshikazuOki,
This is non-repro when following the lab steps in the VM for the course (which has az-cli v 2.17.1 by default, but I also tested after upgrading to 2.26.1). If you're using your own computer, make sure you're in a command prompt terminal, not a PowerShell terminal, and be careful to edit (and save) setup.cmd with your subscription and resource group details as instructed.

**Comment by ToshikazuOki** [comment]
Thank you very much. I was able to get it working by using the latest commit of setup.cmd.
