### ISSUE TITLE
REST API fails due to "gated container". Container should not be gated.

### ISSUE THREAD

**Issue by gottagetgit** [MicrosoftLearning/AI-102-AIEngineer#76]
https://github.com/MicrosoftLearning/AI-102-AIEngineer/blob/268063335f11cb5a7f518f049496a2934877822d/04-containers/rest-test.cmd#L1

I followed the instructions. Deleted the container and tried it again as well. The final step fails because my subscription is "not authorized" to work with the Text Analytics Language container image. But this API should not be gated. It's in general availability according to the documentation.

![Image 2021-07-14 at 7 04 25 PM](https://user-images.githubusercontent.com/1399952/125703955-fe16d1f2-8d11-4481-a461-8a537abbad65.jpeg)

**Comment by GraemeMalcolm** [comment]
I can't repro the issue in the course VM, and the specific container version is not listed as gated.
A couple of things to check:

- It looks like you're using your own dev environment, and running the curl command directly in a PowerShell terminal. Its probably *not* this, but try editing the rest-test.cmd file and running it in a command prompt terminal as instructed.
- Double-check the Billing and ApiKey environment variables you set for the container.
