### ISSUE TITLE
LAb 12, Last section to create a bot for a Knowledge Base - App Service Plan/Location not set automatically 

### ISSUE THREAD

**Issue by janeroughan** [MicrosoftLearning/AI-102-AIEngineer#8]
# Module: 00
#### Step: 02
![Screenshot 2021-01-29 025755](https://user-images.githubusercontent.com/24537110/106164174-d12d3680-61dd-11eb-8f09-7710bacd5796.png)

Description of issue
LAb 12, Last section to create a bot for a Knowledge Base - App Service Plan/Location not set automatically, perhaps I made a mistake in setup?
Repro steps:

1.
1.
1.

**Comment by GraemeMalcolm** [comment]
I've  modified the instruction to create one if it doesn't already exist.
