### ISSUE TITLE
Adding Deployment to Bot Labs

### ISSUE THREAD

**Issue by drguthals** [MicrosoftLearning/AI-102-AIEngineer#83]
# Module: 13
## Description of issue
Often times the deployment from the zip file at the end of the module fails. To avoid this failure during the instructor-led courses, we will move the deployment from the Bot Framework SDK lab to the Bot Composer lab, where deployment happens directly from the Bot Composer webpage.

**Comment by GraemeMalcolm** [comment]
Closing for now as this is a non-blocking issue, tracked in a separate work item
