### ISSUE TITLE
Creating the service principal requires http

### ISSUE THREAD

**Issue by houbena** [MicrosoftLearning/AI-102-AIEngineer#86]
# Module: 2
## Lab/Demo: 02

Description of issue

The command ` az ad sp create-for-rbac -n "https://<spName>" --role owner --scopes subscriptions/<subscriptionId>/resourceGroups/<resourceGroup>`
seems to require `http` instead of `https`.

**Comment by GraemeMalcolm** [comment]
Closing as fixed with api:// update
