### ISSUE TITLE
M04-LAB07 Python lab fails unless neural voice is provided for text-to-speech

### ISSUE THREAD

**Issue by unaihuete93** [MicrosoftLearning/AI-102-AIEngineer#93]
# Module: 04
#### Step: 4

Description of issue

Two students had the same issue `ResultReason.Cancelled` when running the python lab without providing neural voice for the text-to-speech part, looks like the sdk tries to use standard by default. It may be related to this warning:   `...but all new users/new speech resources must choose neural voices` https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/language-support#standard-voices`

Running after completing task **Use a different voice** makes it word (adding the neural voice)
```
// Configure speech synthesis
speechConfig.SpeechSynthesisVoiceName = "en-GB-RyanNeural"; // add this
using SpeechSynthesizer speechSynthesizer = new SpeechSynthesizer(speechConfig);
```

![lab4](https://user-images.githubusercontent.com/64772417/140088875-100580f9-d08a-4305-bb06-c1870855a1ee.png)

**Comment by drguthals** [comment]
Thanks @unaihuete93 

The instructions have been updated for both Python and C# 👍
