### ISSUE TITLE
Module 6 - Building a QnA Solution Lab

### ISSUE THREAD

**Issue by BerndtHamboeck** [MicrosoftLearning/AI-102-AIEngineer#98]
# Module: 06
#### Step: 1-4

Description of issue

The text analytics resource is not available, it should be the QnA service, which could be created after Step one in the Create a knowledge base section.

**Comment by GraemeMalcolm** [comment]
Should probably actually be the Language service.

**Comment by GraemeMalcolm** [comment]
I've updated the lab to use the Language service (and Language Studio instead of the QnA Maker portal)
