### ISSUE TITLE
Lab/Demo: Manage Cognitive Services Security params for az commands

### ISSUE THREAD

**Issue by BerndtHamboeck** [MicrosoftLearning/AI-102-AIEngineer#99]
# Module: 02
#### Step: 01

Description of issue
The set-plicy command needs for the spn the guid, not the name with the latest az powershell commands:
az keyvault set-policy -n keyvault01bh --spn "e61e4e20-e21e-47aa-8f6f-...." --secret-permissions get list

Repro steps:

az ad sp create-for-rbac -n "api://ai-app" --role owner --scopes subscriptions/7132f0e1-4704-4f8e-8a4b-5158c31f6b6a/resourceGroups/ai102

returns a guid for the name:

{
  "appId": "....",
  "displayName": "api://ai-app",
  "name": "e61e4e20-e21e-47aa-8f6f-....",
  "password": "....",
  "tenant": "...."
}

NOTE: --spn: use the guid from the name:
az keyvault set-policy -n keyvault01bh --spn "e61e4e20-e21e-47aa-8f6f-...." --secret-permissions get list

**Comment by C-Youssef** [comment]
FYI, a pull request was submitted more than 2 weeks ago to address this issue. See the pull request "Use Object ID to reference a service principal #95".

**Comment by drguthals** [comment]
Thank you @C-Youssef - I thought I had merged it. It has now been merged.

**Comment by GraemeMalcolm** [comment]
@drguthals , you rock!
Also, you're on holiday - go enjoy your day and we'll handle the rest of this stuff on Monday - risk of loss of life is minimal!
